# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca9a3689c80c61e9066c2761273010615d82f5894ae8de84a2c39236006e519d00ba926014e7174088050e39d1e82c44274731e4335d1158e84be45fcef5399

test:
  secret_key_base: 83c63fed203906c10722498b28be033fc247c092bbc6d072e9e2f5b61e9d3897192953b5db04d978c5d40cdf4612b919e0c36bd0f462325c0c5ec89035055d9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
